import praw

reddit = praw.Reddit('AUTHENTICATION')
COMMENT_ID = 'dja78ia'

comment = reddit.comment(COMMENT_ID)
comment.approved_by()
comment.archived()
comment.author()
comment.author_flair_css_class()
comment.author_flair_text()
comment.banned_by()
comment.block()
comment.body()
comment.body_html()
comment.can_gild()
comment.clear_vote()
comment.controversiality()
comment.created()
comment.created_utc()
comment.delete()
comment.distinguished()
comment.downs()
comment.downvote()
comment.edit(body)
comment.edited()
comment.fullname
comment.gild()
comment.gilded()
comment.id()
comment.is_root
comment.likes()
comment.link_author()
comment.link_id()
comment.link_permalink()
comment.link_title()
comment.link_url()
comment.mark_read()
comment.mark_unread()
comment.mod
comment.mod.approve()
comment.mod.distinguish(how='yes', sticky=False)  # yes, no, admin, special
comment.mod.ignore_reports()
comment.mod.remove(spam=False)
comment.mod_reports()
comment.mod.thing()
comment.mod.undistinguish()
comment.mod.unignore_reports()
comment.name()
comment.num_comments()
comment.num_reports()
comment.over_18()
comment.parent()
comment.parent_id()
comment.permalink(fast=False)
comment.quarantine()
comment.refresh()
comment.removal_reason()
comment.replies
comment.reply(body)
comment.report(reason)
comment.save(category=None)
comment.saved()
comment.score()
comment.score_hidden()
comment.stickied()
comment.submission
comment.subreddit()
comment.subreddit_id()
comment.subreddit_name_prefixed()
comment.subreddit_type()
comment.unsave()
comment.ups()
comment.upvote()
comment.user_reports()
