import praw

reddit = praw.Reddit('AUTHENTICATION')
COMMENT_ID = 'dja78ia'

comment = reddit.comment(COMMENT_ID)
comment.approved
comment.approved_by
comment.archived
comment.author
comment.author.comments
comment.author.controversial
comment.author.downvoted
comment.author.friend
comment.author.friend_info
comment.author.from_data
comment.author.fullname
comment.author.gild
comment.author.gilded
comment.author.gildings
comment.author.hidden
comment.author.hot
comment.author.message
comment.author.multireddits
comment.author.name
comment.author.new
comment.author.parse
comment.author.saved
comment.author.submissions
comment.author.top
comment.author.unblock
comment.author.unfriend
comment.author.upvoted
comment.author_flair_css_class
comment.author_flair_text
comment.banned_by
comment.block()
comment.body
comment.body_html
comment.can_gild
comment.clear_vote()
comment.controversiality
comment.created
comment.created_utc
comment.delete()
comment.distinguished
comment.downs
comment.downvote()
comment.edit(body)
comment.edited
comment.fullname
comment.gild()
comment.gilded
comment.id
comment.ignore_reports
comment.is_root
comment.likes
comment.link_id
comment.mark_read
comment.mark_unread
comment.mod
comment.mod.approve()
comment.mod.distinguish(how='yes', sticky=False)  # yes, no, admin, special
comment.mod.ignore_reports()
comment.mod.remove(spam=False)
comment.mod.thing()
comment.mod.undistinguish()
comment.mod.unignore_reports()
comment.mod_reports
comment.name
comment.num_reports
comment.parent
comment.parent_id
comment.parse
comment.permalink(fast=False)
comment.refresh
comment.removal_reason
comment.removed
comment.replies
comment.reply(body)
comment.report(reason)
comment.report_reasons
comment.save(category=None)
comment.saved
comment.score
comment.score_hidden
comment.spam
comment.stickied
comment.submission
comment.subreddit
comment.subreddit_id
comment.subreddit_name_prefixed
comment.subreddit_type
comment.unsave
comment.ups
comment.upvote
comment.user_reports
