import praw

reddit = praw.Reddit('AUTHENTICATION')
COMMENT_ID = 'abc123'
DOMAIN_NAME = 'site.com'
MULTIREDDIT = 'abc123'
PATH = 'abc123'
FULLNAMES = ['fullnames for a comment, submission, or subreddit']
USERNAME = 'abc123'
SUBMISSION_ID = 'abc123'
SUBREDDIT_NAME = 'abc123'

auth = reddit.auth
auth.authorize(code)
auth.implicit(access_token, expires_in, scope)
auth.limits
auth.scopes()
auth.url(scopes, state, duration='permanent', implicit=False)

comment = reddit.comment(COMMENT_ID)
comment.block()
comment.clear_vote()
comment.delete()
comment.downvote()
comment.edit(body)
comment.fullname
comment.gild()
comment.id()
comment.is_root
comment.mark_read()
comment.mark_unread()
comment.mod
comment.mod.approve()
comment.mod.distinguish(how='yes', sticky=False)  # yes, no, admin, special
comment.mod.ignore_reports()
comment.mod.remove(spam=False)
comment.mod.thing()
comment.mod.undistinguish()
comment.mod.unignore_reports()
comment.parent()
comment.permalink(fast=False)
comment.refresh()
comment.replies
comment.reply(body)
comment.report(reason)
comment.save(category=None)
comment.submission
comment.unsave()
comment.upvote()

config = reddit.config
config.check_for_updates()
config.client_id()
config.client_secret()
config.custom()
config.http_proxy()
config.https_proxy()
config.kinds()
config.oauth_url()
config.password()
config.reddit_url()
config.redirect_uri()
config.refresh_token()
config.short_url()
config.user_agent()
config.username()

domain = reddit.domain(DOMAIN_NAME)
domain.controversial(time_filter='all')  # all, day, hour, month, week, year
domain.hot()
domain.new()
domain.random_rising()
domain.rising()
domain.top(time_filter='all')  # all, day, hour, month, week, year

front = reddit.front
front.comments()
front.controversial()
front.gilded()
front.hot()
front.new()
front.random_rising()
front.rising()
front.top(time_filter='all')  # all, day, hour, month, week, year

inbox = reddit.inbox
inbox.all()
inbox.comment_replies()
inbox.mark_read(items)
inbox.mark_unread(items)
inbox.mentions()
inbox.message(message_id)
inbox.messages()
inbox.sent()
inbox.stream()
inbox.submission_replies()
inbox.unread(mark_read=False)

live = reddit.live
reddit.live.create(title, description=None, nsfw=False, resources=None)
reddit.live.info(ids)
reddit.live.now()

reddit.multireddit.create(display_name, subreddits, description_md=None, icon_name=None, key_color=None, visibility='private', weighting_scheme='classic')
multireddit = reddit.multireddit('samuraisam', 'programming')
multireddit.add(subreddit)
multireddit.comments()
multireddit.comments.gilded()
multireddit.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
multireddit.copy(display_name=None)
multireddit.delete()
multireddit.fullname()
multireddit.gilded()
multireddit.hot()
multireddit.name()
multireddit.new()
multireddit.path()
multireddit.random_rising()
multireddit.remove(subreddit)
multireddit.rename(display_name)
multireddit.rising()
multireddit.sluggify(title)
multireddit.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
multireddit.update(**updated_settings)

random_subreddit = reddit.random_subreddit(nsfw=False)
random_subreddit.banned()
random_subreddit.comments()
random_subreddit.contributor()
random_subreddit.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
random_subreddit.display_name()
random_subreddit.filters()
random_subreddit.flair()
random_subreddit.fullname()
random_subreddit.gilded()
random_subreddit.hot()
random_subreddit.message()
random_subreddit.mod()
random_subreddit.moderator()
random_subreddit.modmail()
random_subreddit.muted()
random_subreddit.new()
random_subreddit.quaran()
random_subreddit.random()
random_subreddit.random_rising()
random_subreddit.rising()
random_subreddit.rules()
random_subreddit.search()
random_subreddit.sticky()
random_subreddit.stream()
random_subreddit.stylesheet()
random_subreddit.submissions()
random_subreddit.submit()
random_subreddit.subscribe()
random_subreddit.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
random_subreddit.traffic()
random_subreddit.unsubscribe()
random_subreddit.wiki()

redditor = reddit.redditor(USERNAME)
redditor.comments()
redditor.comments.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
redditor.comments.hot()
redditor.comments.new()
redditor.comments.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
redditor.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
redditor.downvoted()
redditor.friend(note=None)
redditor.friend_info()
redditor.fullname()
redditor.gild(months=1)
redditor.gilded()
redditor.gildings()
redditor.hidden()
redditor.hot()
redditor.message(subject, message, from_subreddit=None)
redditor.multireddits()
redditor.name()
redditor.new()
redditor.saved()
redditor.submissions()
redditor.submissions.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
redditor.submissions.hot()
redditor.submissions.new()
redditor.submissions.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
redditor.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
redditor.unblock()
redditor.unfriend()
redditor.upvoted()

submission = reddit.submission(SUBMISSION_ID)
submission.clear_vote()
submission.comment_limit()
submission.comment_sort()
submission.comments()
submission.comments.list()
submission.comments.replace_more()
submission.delete()
submission.downvote()
submission.duplicates()
submission.edit(body)
submission.flair()
submission.flair.choices()
submission.flair.select()
submission.flair.submission()
submission.fullname
submission.gild()
submission.gilded()
submission.hide(other_submissions=None)
submission.id()
submission.id_from_url(url)
submission.mod()
submission.mod.approve()
submission.mod.contest_mode(state=True)
submission.mod.distinguish(how='yes', sticky=False)
submission.mod.flair(text='', css_class='')
submission.mod.ignore_reports()
submission.mod.lock()
submission.mod.nsfw()
submission.mod.remove(spam=False)
submission.mod.sfw()
submission.mod.spoiler()
submission.mod.sticky(state=True, bottom=True)
submission.mod.suggested_sort(sort='blank')
submission.mod.thing()
submission.mod.undistinguish()
submission.mod.unignore_reports()
submission.mod.unlock()
submission.mod.unspoiler()
submission.reply(body)
submission.report(reason)
submission.save(category=None)
submission.shortlink
submission.unhide(other_submissions=None)
submission.unsave()
submission.upvote()

reddit.subreddit.create(name, title=None, link_type='any', subreddit_type='public', wikimode='disabled')
reddit.subreddit('all').hot(limit=25)  # Treated differently than a subreddit

subreddit = reddit.subreddit(SUBREDDIT_NAME)
subreddit.banned()
subreddit.banned.add(redditor)
subreddit.banned.relationship()
subreddit.banned.remove(redditor)
subreddit.banned.subreddit()
subreddit.comments()
subreddit.comments.gilded()
subreddit.contributor()
subreddit.contributor.add(redditor, **other_settings)
subreddit.contributor.leave()
subreddit.contributor.relationship()
subreddit.contributor.remove(redditor)
subreddit.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
subreddit.display_name()
subreddit.filters()
subreddit.filters.add(subreddit)
subreddit.filters.remove(subreddit)
subreddit.flair()
subreddit.flair.configure(position='right', self_assign=False, link_position='left', link_self_assign=False, **settings)
subreddit.flair.delete(redditor)
subreddit.flair.delete_all()
subreddit.flair.set(redditor=None, text='', css_class='', thing=None)
subreddit.flair.subreddit()
subreddit.flair.templates()
subreddit.flair.update(flair_list, text='', css_class='')
subreddit.fullname()
subreddit.gilded()
subreddit.hot()
subreddit.message(subject, message, from_subreddit=None)
subreddit.mod()
subreddit.mod.accept_invite()
subreddit.mod.edited(only=None)
subreddit.mod.inbox()
subreddit.mod.log(action=None, mod=None)
subreddit.mod.modqueue(only=None)
subreddit.mod.reports(only=None)
subreddit.mod.settings()
subreddit.mod.spam(only=None)
subreddit.mod.subreddit()
subreddit.mod.unmoderated()
subreddit.mod.unread()
subreddit.mod.update(**settings)
subreddit.moderator()
subreddit.moderator.add(redditor, permissions=None, **other_settings)  # 'access', 'config', 'flair', 'mail', 'posts', 'wiki'
subreddit.moderator.invite(redditor, permissions=None, **other_settings)  # 'access', 'config', 'flair', 'mail', 'posts', 'wiki'
subreddit.moderator.leave()
subreddit.moderator.relationship()
subreddit.moderator.remove(redditor)
subreddit.moderator.remove_invite(redditor)
subreddit.moderator.subreddit()
subreddit.moderator.update(redditor, permissions=None)
subreddit.moderator.update_invite(redditor, permissions=None)
subreddit.modmail()
subreddit.modmail.bulk_read(other_subreddits=None, state=None)
subreddit.modmail.conversations(after=None, limit=None, other_subreddits=None, sort=None, state=None)
subreddit.modmail.create(subject, body, recipient, author_hidden=False)
subreddit.modmail.subreddit()
subreddit.modmail.subreddits()
subreddit.modmail.unread_count()
subreddit.muted()
subreddit.muted.add(redditor)
subreddit.muted.relationship()
subreddit.muted.remove(redditor)
subreddit.new()
subreddit.quaran()
subreddit.quaran.opt_in()
subreddit.quaran.opt_out()
subreddit.random()
subreddit.random_rising()
subreddit.rising()
subreddit.rules()
subreddit.search(query, sort='relevance', syntax='cloudsearch', time_filter='all')
subreddit.sticky(number=1)
subreddit.stream()
subreddit.stream.comments()
subreddit.stream.submissions()
subreddit.stylesheet()
subreddit.stylesheet.delete_header()
subreddit.stylesheet.delete_image(name)
subreddit.stylesheet.delete_mobile_header()
subreddit.stylesheet.delete_mobile_icon()
subreddit.stylesheet.subreddit()
subreddit.stylesheet.update(stylesheet, reason=None)
subreddit.stylesheet.upload(name, image_path)
subreddit.stylesheet.upload_header(image_path)
subreddit.stylesheet.upload_mobile_header(image_path)
subreddit.stylesheet.upload_mobile_icon(image_path)
subreddit.submissions(start=None, end=None, extra_query=None)
subreddit.submit(title, selftext=None, url=None, resubmit=True, send_replies=True)
subreddit.subscribe(other_subreddits=None)
subreddit.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
subreddit.traffic()
subreddit.unsubscribe(other_subreddits=None)
subreddit.wiki()

subreddits = reddit.subreddits
subreddits.default()
subreddits.gold()
subreddits.new()
subreddits.popular()
subreddits.recommended(subreddits, omit_subreddits=None)
subreddits.search()
subreddits.search_by_name(query, include_nsfw=True, exact=Fals)
subreddits.search_by_topic(query)
subreddits.stream(**stream_options)

user = reddit.user
user.blocked()
user.contributor_subreddits()
user.friends()
user.karma()
user.me(use_cache=True)
user.moderator_subreddits()
user.multireddits()
user.subreddits()
