import praw

reddit = praw.Reddit('AUTHENTICATION')

random_subreddit = reddit.random_subreddit(nsfw=False)
random_subreddit.banned()
random_subreddit.comments()
random_subreddit.contributor()
random_subreddit.controversial(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
random_subreddit.display_name()
random_subreddit.filters()
random_subreddit.flair()
random_subreddit.fullname()
random_subreddit.gilded()
random_subreddit.hot()
random_subreddit.message()
random_subreddit.mod()
random_subreddit.moderator()
random_subreddit.modmail()
random_subreddit.muted()
random_subreddit.new()
random_subreddit.quaran()
random_subreddit.random()
random_subreddit.random_rising()
random_subreddit.rising()
random_subreddit.rules()
random_subreddit.search()
random_subreddit.sticky()
random_subreddit.stream()
random_subreddit.stylesheet()
random_subreddit.submissions()
random_subreddit.submit()
random_subreddit.subscribe()
random_subreddit.top(time_filter='all')  # 'all', 'day', 'hour', 'month', 'week', 'year'
random_subreddit.traffic()
random_subreddit.unsubscribe()
random_subreddit.wiki()
