import praw

reddit = praw.Reddit('AUTHENTICATION')
SUBMISSION_ID = 'abc123'

submission = reddit.submission(SUBMISSION_ID)
submission.clear_vote()
submission.comment_limit()
submission.comment_sort()
submission.comments()
submission.comments.list()
submission.comments.replace_more()
submission.delete()
submission.downvote()
submission.duplicates()
submission.edit(body)
submission.flair()
submission.flair.choices()
submission.flair.select()
submission.flair.submission()
submission.fullname
submission.gild()
submission.gilded()
submission.hide(other_submissions=None)
submission.id()
submission.id_from_url(url)
submission.mod()
submission.mod.approve()
submission.mod.contest_mode(state=True)
submission.mod.distinguish(how='yes', sticky=False)
submission.mod.flair(text='', css_class='')
submission.mod.ignore_reports()
submission.mod.lock()
submission.mod.nsfw()
submission.mod.remove(spam=False)
submission.mod.sfw()
submission.mod.spoiler()
submission.mod.sticky(state=True, bottom=True)
submission.mod.suggested_sort(sort='blank')
submission.mod.thing()
submission.mod.undistinguish()
submission.mod.unignore_reports()
submission.mod.unlock()
submission.mod.unspoiler()
submission.reply(body)
submission.report(reason)
submission.save(category=None)
submission.shortlink
submission.unhide(other_submissions=None)
submission.unsave()
submission.upvote()
